# Generated by Django 5.0 on 2023-12-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usern",
            name="password",
            field=models.CharField(default="12345678", max_length=50),
        ),
    ]
